name: scan
description: scan qrcode & barcode in widget tree with custom options.Accurately decode qrcode & barcode image from path.
version: 1.6.0
homepage: https://github.com/flutter-package/flutter_scan

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  plugin:
    platforms:
      android:
        package: com.chavesgu.scan
        pluginClass: ScanPlugin
      ios:
        pluginClass: ScanPlugin

  
